@version 1.2.9
@author Fleeesch
@description paRt
@links
  Website https://fleeesch.github.io/part/index.html
  Reaper Forum Thread https://forum.cockos.com/showthread.php?t=282545
  GitHub Repository https://github.com/Fleeesch/paRt
@screenshots
  Dark Theme - FHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_fhd_dark.png
  Dark Theme - QHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_qhd_dark.png
  Dark Theme - UHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_uhd_dark.png
  Dimmed Theme - FHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_fhd_dimmed.png
  Dimmed Theme - QHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_qhd_dimmed.png
  Dimmed Theme - UHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_uhd_dimmed.png
  Light Theme - FHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_fhd_light.png
  Light Theme - QHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_qhd_light.png
  Light Theme - UHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_uhd_light.png
@provides
  paRt - Dark.ReaperThemeZip https://github.com/Fleeesch/paRt/releases/download/v$version/part_dark.ReaperThemeZip
  paRt - Dimmed.ReaperThemeZip https://github.com/Fleeesch/paRt/releases/download/v$version/part_dimmed.ReaperThemeZip
  paRt - Light.ReaperThemeZip https://github.com/Fleeesch/paRt/releases/download/v$version/part_light.ReaperThemeZip
  [script]paRt/conf/**/*
  [script]paRt/lib/**/*
  [script main]paRt/*.lua
  [data]paRt/splash/*
@about
  # paRt - plain adapting Reaper theme
  
  A custom Reaper theme with a heavy focus on functionality.
  
  * 3 theme variants with different brightness levels and parameter synchronization
  * Full support for zoom factors 100%, 125%, 150%, 175%, 200%, 225%, 250%
  * Complete coverage of all Reaper V7 UI elements
  * Custom Theme Adjuster with extensive configuration options
@changelog
  - Transport: minor formatting tweaks
  - Transport: added project timebase buttons
  - Transport: updated Tap Tempo button to be wider
  - Transport: rearrangement of tempo controls
  - Transport: added BPM label
  - Transport: placed playrate elements in separate section
  - Transport: corrected status bar hiding behaviour
  - TCP: added vertical hiding logic to infobar for modded "tcp_heights"
  - TCP: updated graphics for infobar IO buttons
  - TCP: updated colors for infobar timebase icons
  - Items: updated timebase button assets 
  - Theme Adjuster: added transport timebase-button settings
  - Theme Adjuster: added section toggle for playrate
  - Theme Adjuster: fixed dpi-related jank in "Color Palettes" tab
  - Theme Adjuster: several colors and label tweaks
