@version 1.2.8
@author Fleeesch
@description paRt
@links
  Website https://fleeesch.github.io/part/index.html
  Reaper Forum Thread https://forum.cockos.com/showthread.php?t=282545
  GitHub Repository https://github.com/Fleeesch/paRt
@screenshots
  Dark Theme - FHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_fhd_dark.png
  Dark Theme - QHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_qhd_dark.png
  Dark Theme - UHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_uhd_dark.png
  Dimmed Theme - FHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_fhd_dimmed.png
  Dimmed Theme - QHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_qhd_dimmed.png
  Dimmed Theme - UHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_uhd_dimmed.png
  Light Theme - FHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_fhd_light.png
  Light Theme - QHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_qhd_light.png
  Light Theme - UHD https://fleeesch.github.io/part/res/gallery/sshot/part_res_uhd_light.png
@provides
  paRt - Dark.ReaperThemeZip https://github.com/Fleeesch/paRt/releases/download/v$version/part_dark.ReaperThemeZip
  paRt - Dimmed.ReaperThemeZip https://github.com/Fleeesch/paRt/releases/download/v$version/part_dimmed.ReaperThemeZip
  paRt - Light.ReaperThemeZip https://github.com/Fleeesch/paRt/releases/download/v$version/part_light.ReaperThemeZip
  [script]paRt/conf/**/*
  [script]paRt/lib/**/*
  [script main]paRt/*.lua
  [data]paRt/splash/*
@about
  # paRt - plain adapting Reaper theme
  
  A custom Reaper theme with a heavy focus on functionality.
  
  * 3 theme variants with different brightness levels and parameter synchronization
  * Full support for zoom factors 100%, 125%, 150%, 175%, 200%, 225%, 250%
  * Complete coverage of all Reaper V7 UI elements
  * Custom Theme Adjuster with extensive configuration options
@changelog
  - TCP: updated infobox IO icons
  - TCP: meter can be optionally displayed in collapsed mode
  - TCP: infoblock doesn't extend label size when activated unless there's not enough room
  - TCP: tweaked minimal height threshold values for modded "tcp_heights"
  - TCP: added ENVCP hiding logic for small height for modded "tcp_heights"
  - TCP: corrected ENVCP folder line margins
  - Meters: added parameters for controlling the gain reduction meter gap and width
  - Meters: better alpha-calibration for meter text overlay
  - Meters: fixed missing unlit-text-shadow for TCP
  - Theme Adjuster: fixed potential drawing error on theme-error-message-display
  - Theme Adjuster: split TCP Track section into 2 tabs
  - Theme Adjuster: added option to show meter in TCP track collapsed mode
  - Theme Adjuster: additional layout changes for more streamlined experience
  - fixed multiple instances of readme comment section in rtconfig.txt
  - updated pinned tracks divider line colors
